### ISSUE TITLE
인덱스로 원소 선택하는 경우, 대괄호 사용 유무

### ISSUE THREAD

**Issue by silent-june** [yoUschool-DS/DA_BookStudy#2]
> Case1

`print(sr[0]) # sr 시리즈의 1번째 원소를 선택(정수형 위치)`
`print(sr['이름']) # '이름' 라벨을 가진 원소를 선택(인덱스 이름)`

> Case2

`print(sr[[1, 2]])`
`print(sr[['생년월일', '성별']])`

> Case3

`print(sr[1:2])`
`print(sr['생년월일':'성별'])`

질문1. 인덱스를 하나만 선택하는 경우에는 데이터값만 반환이 되는데, 왜 여러 원소를 지정하면 인덱스 이름도 같이 출력이 되는가
질문2. 원소를 여러개 선택할 때, 내부에 대괄호를 하나 더 넣어야하는 것이라면 왜 범위지정을 할 때는 추가적으로 대괄호를 사용할 필요가 없는가

**Comment by sono9805** [comment]
질문1. 인덱스를 하나만 선택하는 경우에는 데이터값만 반환이 되는데, 왜 여러 원소를 지정하면 인덱스 이름도 같이 출력이 되는가

답변1. Series 객체에서 여러 원소를 선택하면 인덱스 이름을 포함한 시리즈 값으로 반환하기 때문이다. 하나만 선택하는 경우는 인덱스 이름을 반환할 필요가 없다. 배열 데이터가 아니기 때문에 인덱스 이름을 활용하여 데이터를 추출, 활용할 일이 없으니까.

```
data = ['손정호','남성','1998-05-08',23, True]
sr = pd.Series(data)
sr2 = sr[[1,2]]

```
```
print(type(sr))
#출력값 : pandas.core.series.Series
print(type(sr2))
#출력값 : pandas.core.series.Series
```

+) 단, 정수형 위치 인덱스는 시리즈 객체 내의 원소의 상대적 위치이기 때문에 반환하지 않는다. (아래 보면 달라져있음)

```
#sr출력값
0           손정호
1            남성
2    1998-05-08
3            23
4          True
dtype: object

#sr2출력값
1            남성
2    1998-05-08
dtype: object

```


(Pandas에서 Series, DataFrame 객체가 인덱스 활용 가능하나 sr로 쓴 것으로 보아 **시리즈로 가정**하고 답변함.)

**Comment by sono9805** [comment]
질문2. 원소를 여러개 선택할 때, 내부에 대괄호를 하나 더 넣어야하는 것이라면 왜 범위지정을 할 때는 추가적으로 대괄호를 사용할 필요가 없는가

답변2. 용준은 인덱싱 방법 중 "원소를 넣는 것"과 "범위를 넣는 것"으로 생각하고 있는 듯 하나. 인덱싱(특정 원소 선택)과 슬라이싱(범위로 지정)는 다른 개념이라 문법과 내용이 다른게 너무 당연?.. (왜 슬라이싱 할 때, 인덱싱의 문법을 따를 필요가 없는가?라는 질문임.) 



+)

다만 용준이가 궁금한건 **왜 범위 지정할 때는 대괄호를 안넣는가?** = **왜 여러 원소 선택 시에 리스트 형태로 입력하는가** 
두 가지인 듯하여, 인덱싱할 때 2개 이상의 인덱스 이름/정수형 인덱스를 리스트 형식으로 넣어야 하는 이유를 생각해보았습니다.

그건 df로 넘어가게 되면 콤마(,)가 행/열을 나눠주는 기호가 되기 때문입니다.(인덱스/슬라이싱 방법은 sr, df가 동일하기 때문이쥬)
그 상황에 2개 이상 인덱스를 []로 구분지어주지 않는다면, 

"정호", "용준" 행에서 "나이"를 인덱스하고 싶을 때, **df["정호", "용준", "나이"]**가 되겠죠?..ㅠㅠ
그럼 저를 떠나서,, 컴퓨터부터 어디를 행열로 봐야할지 파악하지 못할 듯 하네요.
