### ISSUE TITLE
df.loc[행,열]과 df.loc[행][열]의 차이점

### ISSUE THREAD

**Issue by sono9805** [yoUschool-DS/DA_BookStudy#3]
(책 p.35)

```
import pandas as pd
exam_data = {"이름" : ["서준", "우현", "민아"], "수학" : [90,80,70], "영어" : [98,89,95], "윤리" : [85,95,100])

df = pd.DataFrame(exam_data)

df.set_index("이름", inplace = True)
```

여기서 "서준"의 "수학", "윤리" 성적을 df.loc로 선택하고자 하면

`df.loc["서준", ["수학", "윤리"]
`
이렇게 코드를 작성할 수 있다. 

근데, df.loc["서준"]["수학","윤리"]를 실행해도 위의 코드와 동일한 결과가 나오는데

**df.loc[행,열]과 df.loc[행][열]의 차이점**은 무엇일까?.. (어떤 상황에서 써야 더 적합한가?) 

+) df.loc[행][열] = df.loc[행, 열]인 줄 알았는데

df.loc[:][2개 이상의 인덱스 이름]을 넣으면 error가 뜬다. 왜 그럴까?.. 
(예상하는 원인 : df.loc[행][열]에서는 인덱싱과 슬라이싱을 혼용할 수 없나?)

**Comment by silent-june** [comment]
> 질문1. df.loc[행,열]과 df.loc[행][열]의 차이점은 무엇일까?..
 
**어떤 상황에서 써야 더 적합한가는 본인의 취향이라고 생각합니다!**

pandas에서 개체를 구분하는 방식은 크게 두 가지인 것 같아요.
1번. ','를 사용하여 개체를 구분시켜준다
2번. 대괄호를 사용하여 개체를 구분시켜준다

즉, 하나의 대괄호 안에는 낱개로 분리될 수 있는 덩어리가 들어가야 하지만, 예외적으로 대괄호 내부에 콤마를 사용했을 경우 낱개를 여러 개 나열하는 것을 허용하는 것이지요!

중요한 것은 두 방식의 차이점이 아니라, 둘 모두 하나의 대괄호 안에는 하나의 덩어리만 넣으려고 한다는 것입니다!

행과 열을 굳이굳이 구분해야만 명확하게 알 수 있는 상황이 아니라면, 콤마가 여러모로 효율적일 것 같네요! 대괄호의 개수가 많아지면 열고 닫는 것도 제대로 했는지 신경써야하고!

> 질문2. df.loc[:][2개 이상의 인덱스 이름]을 넣으면 error가 뜬다. 왜 그럴까?..


요것은 제가 생각하기에는..
`print(df.loc[:])`
를 하게 될 경우, 행 인덱스만 출력되는 것이 아니라 열 이름까지 같이 출력되는 것을 확인할 수 있는데, 결국 df.loc[:]는 행과 열을 둘 다 포괄하는 코드라는 것을 1차적으로 확인할 수 있습니다.

게다가, 소노가 말씀하신 것처럼 인덱싱과 슬라이싱을 혼용해도 오류가 뜨는 것을 알 수 있죠. 그렇다면 오류의 원인은 두 가지 중 하나로 귀결되어야 합니다.

1. [:]가 행과 열을 둘 다 포괄하는 개념이기 때문에 뒤에 추가적인 대괄호가 나올 수 없다
2. 인덱싱과 슬라이싱을 혼용하는 것이 불가능하다. 

일단 2번을 먼저 검증하기 위해서
`print(df.loc[[:][0:2]])`
를 출력해보면, 오류가 나오는 것을 확인할 수 있습니다.
행과 열 모두 슬라이싱을 사용했음에도 출력이 되지 않는다는 것, 그리고 오류의 원인이 [:]에 있다고 표시되는 것을 보았을 때, 오류의 원인이 2번은 아니라는 것을 확인할 수 있습니다.

그렇다면 오류의 원인은 1번이라는 것인데, 이를 검증하기 위해서 행 인덱스에 [:]를 이미 사용했을 경우, 열 이름에는 어떠한 항목도 선택할 수 없는가를 체크해보았습니다.

다른 코드는 모두 오류가 나고, 유일하게 사용할 수 있던 열 이름은,
`df.loc[:][:]` 였네요.
즉, [:]을 사용할 때는 전체 데이터프레임을 출력해야만 오류가 나지 않는다는 것을 확인할 수 있었습니다.

**Comment by sono9805** [comment]
Q1. df.loc[[:][0:2]]는 판다스 문법 상 오류 아닌가.ㅠㅠ.

Q2. df.loc[:]["열 이름 1개"]인 경우는 출력이 되어..뒤에 추가적인 대괄호가 붙는건 가능..

**Comment by sono9805** [comment]
결론) 둘 모두 하나의 대괄호 안에는 하나의 덩어리만 넣으려고 한다는 것
