### ISSUE TITLE
<예제 3-1> p85. df.head() 출력 여부

### ISSUE THREAD

**Issue by silent-june** [yoUschool-DS/DA_BookStudy#4]
논리적인 이해의 영역에 대한 질문은 아닙니다만,,,

해당 예제의 마지막 줄을 보면 df.head()가 아니라
print(df.head())로 출력을 해놨길래

df.head()로 출력을 해봤거든요??

그런데 df.tail()은 출력이 되는데 df.head()는 출력이 안 되어서.. 요것이 비단 저만의 문제인 것인지 궁금하네요..

**Comment by sono9805** [comment]
HELLO june.

It seems like that your problem is only on you and come from VS code. 
^^~ Why don't you use Jupyter notebook instead of VS?. 


![image](https://user-images.githubusercontent.com/63627319/107917602-8700cf00-6fab-11eb-84f3-30ae0a37f022.png)

**Comment by sono9805** [comment]
HELLO june.

It seems like that the problem is only on you and comes from VS code.
^^~ Why don't you use Jupyter notebook instead of VS?.
![image](https://user-images.githubusercontent.com/63627319/107917851-eb239300-6fab-11eb-937e-2405794847ca.png)

**Comment by silent-june** [comment]
유감 ^_^

**Comment by silent-june** [comment]
왜 저는 주피터 노트북으로 들어가도 안되는 걸까요 ㅠㅠ
