### ISSUE TITLE
<예제 4-1> df.read_excel()에서 fillna 키워드 사용 가능 여부

### ISSUE THREAD

**Issue by sono9805** [yoUschool-DS/DA_BookStudy#5]
![image](https://user-images.githubusercontent.com/63627319/107924719-c680e880-6fb6-11eb-9c4f-54784416516d.png)

실행하면 에러 메세지가 뜨는데
**( read_excel() got an unexpected keyword argument 'fillna')**

이거 저만 그런가요? 소스코드에도 똑같이 있는데 도대체 왜 ㅠㅠ;;;;;;

**Comment by silent-june** [comment]
저도 지금 같은 오류가 나고 있어서 한 단계씩 해결해보고 있는데,,,

df = pd.read_excel('./시도별 전출입 인구수.xlsx', header=0).fillna(0)

이걸로 한 번 시도해보시겠어요?
