### ISSUE TITLE
<예제 4-13> DataFrame 객체를 데이터로 활용하여 화면 n분할 그래프 표현하는 방법  

### ISSUE THREAD

**Issue by sono9805** [yoUschool-DS/DA_BookStudy#6]
p.126에서 4분할 그래프를 출력하는 방법을 배웠는데, 
아래의 방법은 plot() 함수의 인자로 x축 데이터, y축 데이터를 시리즈로 추출하여 직접 입력하는 방법입니다.

1) fig = plt.figure()로 그래프의 초기 figure을 만들고
2) axes = fig.add_subplot()으로 몇행X몇열의 좌표평면에 subplot을 표현할 것인지 지정하고
3) 2)에서 만든 객체(axes)에서 plot() 함수로 그래프를 출력한다.

그렇다면, <예제 4-13>처럼 4개의 열 데이터로 구성된 면적 그래프를 
n분할한 그래프에 subplot으로 넣고 싶을 때는 어떻게 해야 할까요?

앞서 4개의 데이터를 한 그래프에 입력하는 방법 <예제 4-10>
DF에서 시리즈 추출하여 plot()함수 인자에 넣는 방법

을 배우긴했는데, 이걸 동시에 쓰려고 하니 넘 비효율적인 듯 하여
예제 <4-13>의 37라인 이후 df_4를 수정없이(특히 막 loc써서 행, 열 데이터 시리즈로 추출하는거 ㄹㅇ 싫어요) 활용할 방법이 궁금하네요.

**Comment by silent-june** [comment]
정호님이 말씀하시는 것이,
ax1,ax2,ax3,ax4 자체를 만드는 것을 방지하고 싶다는 것일까요..?
아니면 subplot자체는 어쩔 수 없이 만들어야하지만, 그 인수를 집어넣는 과정이 넘나 귀찮다는 것일까요..?
아니면 둘 다이려나...?

조금 더 효율적인 방법이 있을까 하여 그 부분은 계속 찾아보았지만,, 저는 현재 주어진 방법밖에는 보이지가 않습니다..! 혹시 몰라 구글의 힘도 조금은 빌려보았지만, 책에서 설명하는 내용을 반복해서 설명할 뿐, df_4의 행 열을 직접 추출해서 사용해야할 것 같아유
